/**
 * Список регионов с приблизительными центрами.
 * id   — ключ для сопоставления со статусами оповещений.
 * country — "UA" или "RU" (для группировки в интерфейсе).
 * lat/lng — центр региона для маркера на карте.
 */
window.REGIONS = [
  // --- Украина ---
  { id: "vinnytsia", country: "UA", name: "Винницкая область", lat: 49.233, lng: 28.468 },
  { id: "volyn", country: "UA", name: "Волынская область", lat: 50.747, lng: 25.325 },
  { id: "dnipro", country: "UA", name: "Днепропетровская область", lat: 48.464, lng: 35.046 },
  { id: "donetsk", country: "UA", name: "Донецкая область", lat: 48.015, lng: 37.803 },
  { id: "zhytomyr", country: "UA", name: "Житомирская область", lat: 50.255, lng: 28.658 },
  { id: "zakarpattia", country: "UA", name: "Закарпатская область", lat: 48.621, lng: 22.288 },
  { id: "zaporizhzhia", country: "UA", name: "Запорожская область", lat: 47.838, lng: 35.139 },
  { id: "ivano-frankivsk", country: "UA", name: "Ивано-Франковская область", lat: 48.922, lng: 24.711 },
  { id: "kyiv-oblast", country: "UA", name: "Киевская область", lat: 50.053, lng: 30.766 },
  { id: "kyiv-city", country: "UA", name: "г. Киев", lat: 50.4501, lng: 30.5234 },
  { id: "kirovohrad", country: "UA", name: "Кировоградская область", lat: 48.508, lng: 32.262 },
  { id: "luhansk", country: "UA", name: "Луганская область", lat: 48.574, lng: 39.308 },
  { id: "lviv", country: "UA", name: "Львовская область", lat: 49.84, lng: 24.03 },
  { id: "mykolaiv", country: "UA", name: "Николаевская область", lat: 46.975, lng: 31.995 },
  { id: "odesa", country: "UA", name: "Одесская область", lat: 46.485, lng: 30.733 },
  { id: "poltava", country: "UA", name: "Полтавская область", lat: 49.589, lng: 34.551 },
  { id: "rivne", country: "UA", name: "Ровенская область", lat: 50.619, lng: 26.251 },
  { id: "sumy", country: "UA", name: "Сумская область", lat: 50.907, lng: 34.799 },
  { id: "ternopil", country: "UA", name: "Тернопольская область", lat: 49.553, lng: 25.595 },
  { id: "kharkiv", country: "UA", name: "Харьковская область", lat: 49.993, lng: 36.231 },
  { id: "kherson", country: "UA", name: "Херсонская область", lat: 46.635, lng: 32.616 },
  { id: "khmelnytskyi", country: "UA", name: "Хмельницкая область", lat: 49.423, lng: 26.987 },
  { id: "cherkasy", country: "UA", name: "Черкасская область", lat: 49.444, lng: 32.06 },
  { id: "chernivtsi", country: "UA", name: "Черновицкая область", lat: 48.292, lng: 25.935 },
  { id: "chernihiv", country: "UA", name: "Черниговская область", lat: 51.498, lng: 31.289 },

  // --- Россия ---
  { id: "ru-belgorod", country: "RU", name: "Белгородская область", lat: 50.595, lng: 36.587 },
  { id: "ru-bryansk", country: "RU", name: "Брянская область", lat: 53.243, lng: 34.364 },
  { id: "ru-kursk", country: "RU", name: "Курская область", lat: 51.731, lng: 36.193 },
  { id: "ru-voronezh", country: "RU", name: "Воронежская область", lat: 51.672, lng: 39.184 },
  { id: "ru-rostov", country: "RU", name: "Ростовская область", lat: 47.235, lng: 39.701 },
  { id: "ru-krasnodar", country: "RU", name: "Краснодарский край", lat: 45.035, lng: 38.975 },
  { id: "ru-volgograd", country: "RU", name: "Волгоградская область", lat: 48.708, lng: 44.513 },
  { id: "ru-lipetsk", country: "RU", name: "Липецкая область", lat: 52.61, lng: 39.594 },
  { id: "ru-tula", country: "RU", name: "Тульская область", lat: 54.193, lng: 37.617 },
  { id: "ru-oryol", country: "RU", name: "Орловская область", lat: 52.97, lng: 36.064 },
  { id: "ru-smolensk", country: "RU", name: "Смоленская область", lat: 54.782, lng: 32.045 },
  { id: "ru-moscow-oblast", country: "RU", name: "Московская область", lat: 55.508, lng: 37.954 },
  { id: "ru-istra", country: "RU", name: "МО Истра", lat: 55.914, lng: 36.868 },
  { id: "ru-moscow", country: "RU", name: "г. Москва", lat: 55.7558, lng: 37.6173 },
  { id: "ru-kaluga", country: "RU", name: "Калужская область", lat: 54.513, lng: 36.261 },
  { id: "ru-ryazan", country: "RU", name: "Рязанская область", lat: 54.625, lng: 39.736 },
  { id: "ru-tambov", country: "RU", name: "Тамбовская область", lat: 52.721, lng: 41.452 },
  { id: "ru-saratov", country: "RU", name: "Саратовская область", lat: 51.533, lng: 46.034 },
  { id: "ru-penza", country: "RU", name: "Пензенская область", lat: 53.195, lng: 45.018 },
  { id: "ru-tver", country: "RU", name: "Тверская область", lat: 56.859, lng: 35.912 },
  { id: "ru-yaroslavl", country: "RU", name: "Ярославская область", lat: 57.626, lng: 39.894 },
  { id: "ru-vladimir", country: "RU", name: "Владимирская область", lat: 56.129, lng: 40.407 },
  { id: "ru-ivanovo", country: "RU", name: "Ивановская область", lat: 56.997, lng: 40.973 },
  { id: "ru-nnovgorod", country: "RU", name: "Нижегородская область", lat: 56.227, lng: 44.0 },
  { id: "ru-ulyanovsk", country: "RU", name: "Ульяновская область", lat: 54.317, lng: 48.402 },
  { id: "ru-samara", country: "RU", name: "Самарская область", lat: 53.241, lng: 50.221 },
  { id: "ru-astrakhan", country: "RU", name: "Астраханская область", lat: 46.348, lng: 48.034 },
  { id: "ru-stavropol", country: "RU", name: "Ставропольский край", lat: 45.043, lng: 41.969 },
  { id: "ru-adygea", country: "RU", name: "Республика Адыгея", lat: 44.6, lng: 40.1 },
  { id: "ru-crimea", country: "RU", name: "Республика Крым", lat: 45.3, lng: 34.4 },
  { id: "ru-mordovia", country: "RU", name: "Республика Мордовия", lat: 54.18, lng: 44.45 },
  { id: "ru-chuvashia", country: "RU", name: "Чувашская Республика", lat: 55.5, lng: 47.0 },
  { id: "ru-tatarstan", country: "RU", name: "Республика Татарстан", lat: 55.6, lng: 50.0 },
  { id: "ru-spb", country: "RU", name: "г. Санкт-Петербург", lat: 59.9311, lng: 30.3609 },
  { id: "ru-leningrad", country: "RU", name: "Ленинградская область", lat: 60.0, lng: 31.5 },
];
